
variables:
    BASE_DISTROS: 'kali-rolling'  # 'kali-rolling kali-dev kali-last-snapshot'
    EXTRA_DISTROS: 'kali-experimental'  # 'kali-experimental kali-bleeding-edge'
    ARCHS: 'arm64'  # 'amd64 arm64 armhf'

stages:
    - build
    - register
    - test
    - push

build-rootfs:
    stage: build
    image: debian:testing
    artifacts:
        paths:
            - "*.tar.xz"
            - "*.release.version"
    script: |
        set -e
        # Install tools
        apt-get -y update
        apt-get -y install debootstrap pixz qemu-user-static wget
        # Install Kali archive keyring
        KEYRING_PKG_URL=$(wget -nv -O - \
            http://http.kali.org/kali/dists/kali-rolling/main/binary-amd64/Packages.gz \
            | gzip -dc | grep ^Filename: | grep kali-archive-keyring | head -n 1 | awk '{print $2}')
        KEYRING_PKG_URL="http://http.kali.org/kali/$KEYRING_PKG_URL"
        wget -nv "$KEYRING_PKG_URL"
        dpkg -i kali-archive-keyring_*_all.deb
        rm kali-archive-keyring_*_all.deb
        # Enable support for additional executable binary formats
        update-binfmts --enable
        echo "Kernel details: $(uname -a)"
        echo "Executable binary formats:"
        #update-binfmts --display | grep -v = | sed -e 's/^/  /' -e 's/:$//'
        update-binfmts --display
        # Monkey patch debootstrap to properly detect docker
        if [ -z "$(. /usr/share/debootstrap/functions && detect_container && echo $CONTAINER)" ]; then
            echo "PATCHING DEBOOTSTRAP TO FIX DOCKER DETECTION cf. #985481"
            sed -E -i 's;(proc/1/mountinfo);\1 || [ -e /.dockerenv ];' /usr/share/debootstrap/functions
        fi
        # Since GitLab migrated to Google Container-Optimized OS & Docker 19.03.15
        # in August 2021, /builds is mounted with the option nodev, and it breaks
        # debootstrap. Workaround by using another location.
        # References:
        # * https://gitlab.com/kalilinux/build-scripts/kali-docker/-/issues/40
        # * https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5184
        mkdir /work && cp build-rootfs.sh /work && cd /work
        # Build the various rootfs
        for distro in $BASE_DISTROS; do
            for arch in $ARCHS; do
                echo "========================================"
                echo "Building rootfs $distro/$arch"
                echo "========================================"
                ./build-rootfs.sh "$distro" "$arch"
            done
        done
        # Bring artifacts back in CI_PROJECT_DIR (see above)
        cp -v *.tar.xz *.release.version $CI_PROJECT_DIR

build-docker-images:
    stage: register
    image: debian:testing
    dependencies:
        - build-rootfs
    artifacts:
        paths:
            - "*.conf"
    script: |
        set -e
        apt-get -y update
        apt-get -y install ca-certificates podman
        echo "$CI_JOB_TOKEN" | podman login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
        for distro in $BASE_DISTROS; do
            for arch in $ARCHS; do
                ./podman-build.sh "$distro" "$arch"
            done
        done
        for distro in $EXTRA_DISTROS; do
            for arch in $ARCHS; do
                ./podman-build-extra.sh "$distro" "$arch"
            done
        done

test-docker-images:
    stage: test
    image: debian:testing
    dependencies:
        - build-docker-images
    script: |
        set -e
        apt-get -y update
        apt-get -y install podman
        for distro in $BASE_DISTROS $EXTRA_DISTROS; do
            for arch in $ARCHS; do
                ./podman-test.sh "$distro" "$arch"
            done
        done

push-docker-images:
    stage: push
    image: debian:testing
    dependencies:
        - build-docker-images
    script: |
        set -e
        apt-get -y update
        apt-get -y install ca-certificates podman
        echo "$CI_JOB_TOKEN" | podman login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
        if [ -n "$DOCKER_HUB_ACCESS_TOKEN" ]; then
            echo "$DOCKER_HUB_ACCESS_TOKEN" | podman login -u "$DOCKER_HUB_USER" --password-stdin "$DOCKER_HUB_REGISTRY"
        fi
        for distro in $BASE_DISTROS $EXTRA_DISTROS; do
            for arch in $ARCHS; do
                ./podman-push.sh "$distro" "$arch"
            done
        done
        for distro in $BASE_DISTROS $EXTRA_DISTROS; do
            ./podman-push-manifest.sh "$distro" "$ARCHS"
        done
        # Clean tags
        #apk add curl jq gawk
        #for distro in $BASE_DISTROS $EXTRA_DISTROS; do
        #    for arch in $ARCHS; do
        #        ./docker-cleanup.sh "$distro" "$arch"
        #    done
        #done
